In [1]:
print ("Hello")

Hello


In [3]:
print ("hello")


hello


In [4]:
a=[1,2,3,4,5,6,7,8,9]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
type(a)

list

In [6]:
import numpy as np



In [8]:
np.array(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b=np.array(a)

In [12]:

b=np.array(a)
type(b)


numpy.ndarray

In [14]:
nparray.size(a)

NameError: name 'nparray' is not defined

In [15]:
a.ndsize


AttributeError: 'list' object has no attribute 'ndsize'

In [44]:
a=([[[[[1,2,3],[4,5,6],[7,8,9]]]]])
type(a)

list

In [45]:
b=np.array(a)
print(b)


[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]


In [46]:
type(b)

numpy.ndarray

In [47]:
b.ndim

5

In [48]:
b.shape

(1, 1, 1, 3, 3)

In [49]:
b.size

9

In [50]:
b.dtype

dtype('int64')

In [54]:
b.itemsize

8

In [53]:
b.data