In [1]:
import numpy as np

In [64]:
r=np.array([[[12,25,36],[74,85,62],[52,64,41]]])
print(r)

[[[12 25 36]
  [74 85 62]
  [52 64 41]]]


In [68]:
r.sort(axis=0)
r

array([[[12, 25, 36],
        [52, 64, 41],
        [74, 85, 62]]])

In [66]:
r.size

9

In [67]:
r.ndim

3

In [15]:
r.itemsize

8

In [16]:
p=np.zeros([5,4])
print(p)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
p=np.full((5,2),6)
print(p)

[[6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]]


In [21]:
np.random.rand(3,4)

array([[0.28174514, 0.27193959, 0.38855   , 0.10428405],
       [0.84100318, 0.74177427, 0.97768718, 0.00662312],
       [0.15578991, 0.50955969, 0.07426704, 0.5567594 ]])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.copy(r)

array([[[12, 25, 36],
        [62, 74, 85],
        [41, 52, 64]],

       [[52, 69, 71],
        [67, 84, 95],
        [13, 68, 74]]])

In [24]:
view(dtype)

NameError: name 'view' is not defined

In [38]:
r.sort(axis=0)
print(r)

[[[12 25 36]
  [13 52 64]
  [62 74 85]]

 [[41 68 71]
  [52 69 74]
  [67 84 95]]]


In [37]:
r.sort(axis=1)
print(r)

[[[12 25 36]
  [13 52 64]
  [62 74 85]]

 [[41 68 71]
  [52 69 74]
  [67 84 95]]]


In [75]:
z=np.append(r,[87,65,48])
print(z)


[12 25 36 52 64 41 74 85 62 87 65 48]


In [76]:
z


array([12, 25, 36, 52, 64, 41, 74, 85, 62, 87, 65, 48])

In [77]:
z.sort()
z


array([12, 25, 36, 41, 48, 52, 62, 64, 65, 74, 85, 87])

In [81]:
k=np.insert(z,4,[78,61,14])
k

array([12, 25, 36, 41, 78, 61, 14, 48, 52, 62, 64, 65, 74, 85, 87])

In [86]:
k=np.delete(z,1,axis=0)
k

array([12, 36, 41, 48, 52, 62, 64, 65, 74, 85, 87])

In [92]:
z.shape

(12,)

In [93]:
z.reshape(4,3)

array([[12, 25, 36],
       [41, 48, 52],
       [62, 64, 65],
       [74, 85, 87]])